---
title: "Tuesday Talk Figures"
author: "Rachael Caelie (Rocky) Aikens"
date: "10/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center")
library(confirmationBias)
library(tidyverse)
library(ggpubr)
library(knitr)
library(binom)

set.seed(123)

theme_set(theme_light())
```

# Case 0: Diagnosis depends on Representativeness only

## Phi Function

```{r fig.height=3, fig.width=3}
R <- seq(0, 1, length.out = 100)

ggplot(data = data.frame(R), aes(x = R, y = diagnosis_fn(R, 0, theta = c(-10, 20, 0)))) +
  geom_line() + xlim(c(0,1)) + ylim(c(0,1)) + coord_fixed()+
  ylab("P(Diagnosis | R)")
```

```{r}
set.seed(123)

n <- 50000
df <- generate_cross_sectional(n = n) %>%
  diagnose_cross_sectional(theta = c(-10, 20, 0))
```


## Prevalence

```{r fig.height=3, fig.width=3}
# Final version
plt_data <- rbind(binom.confint(sum(df$diagnose), dim(df)[1], method = "asymptotic"), 
      binom.confint(sum(df$disease), dim(df)[1], method = "asymptotic")) %>%
  rename(diagnosed = x, Prevalence = mean) %>%
  mutate(status = c("Observed", "Actual"))

plt_data[2, 5:6] <- NA

ggplot(plt_data, aes(x = status, y = Prevalence, alpha = status)) +
  geom_col() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25) +
  labs(title = "Disease Prevalence") +
  scale_alpha_manual(values = c(0.6, 1), guide = "none") + 
  theme(axis.title.x = element_blank()) +
  ylim(c(0,0.2))

plt_data[2,4] <- NA

ggplot(plt_data, aes(x = status, y = Prevalence, alpha = status)) +
  geom_col() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25) +
  labs(title = "Disease Prevalence") +
  scale_alpha_manual(values = c(0.6, 1), guide = "none") + 
  theme(axis.title.x = element_blank()) +
  ylim(c(0,0.2))
```
## Representativeness

```{r fig.height=3, fig.width=4.5}
diseased <- df %>% filter(disease == TRUE) %>%
  mutate(group = "Have disease")

diagnosed <- df %>% filter(diagnosed == TRUE) %>%
  mutate(group = "Diagnosed")

plt_data <- rbind(diseased, diagnosed)

ggplot(plt_data, aes(x = representativeness, group = group, alpha = group)) +
  geom_histogram(position = "identity") +
  scale_alpha_manual(values = c(1, 0.6)) +
  labs(title = "Distribution of disease representativeness", x = "Representativeness", y = "Number of individuals") +
  theme(legend.title = element_blank())

ggplot(plt_data, aes(x = representativeness, group = group, alpha = group)) +
  geom_histogram(position = "identity") +
  scale_alpha_manual(values = c(1, 0)) +
  labs(title = "Distribution of disease representativeness", x = "Representativeness", y = "Number of individuals") +
  theme(legend.title = element_blank())

```

# Case 1: Diagnosis depends on representativeness and demographics

## Phi Function

```{r, fig.height=3, fig.width=3}
R <- seq(0, 1, length.out = 100)

plt_data <- expand.grid(R, c(0,1)) %>%
  rename(R = Var1, X = Var2) %>%
  mutate(phi = diagnosis_fn(representativeness = R, x = X, theta = c(-10, 20, -5))) %>%
  mutate(X = as.factor(X))

ggplot(data = plt_data, aes(x = R, y = phi, group = X, color = X)) +
  geom_line() + xlim(c(0,1)) + ylim(c(0,1)) + coord_fixed() +
  scale_color_brewer(palette = "Set1", direction = -1)+
  ylab("P(Diagnosis | R)")
```

## Prevalence

```{r}
n <- 50000
df <- generate_cross_sectional(n = n) %>%
  diagnose_cross_sectional()
```

```{r fig.height=3, fig.width=3}
df_x1 <- filter(df, x == 1)
df_x0 <- filter(df, x == 0)

plt_data <- rbind(binom.confint(sum(df_x1$diagnose), dim(df_x1)[1], method = "asymptotic"), 
      binom.confint(sum(df_x0$diagnose), dim(df_x0)[1], method = "asymptotic"),
      binom.confint(sum(df_x1$disease), dim(df_x1)[1], method = "asymptotic"),
      binom.confint(sum(df_x0$disease), dim(df_x0)[1], method = "asymptotic")) %>%
  rename(diagnosed = x, Prevalence = mean) %>%
  mutate(x = as.factor(c(1, 0, 1, 0)),
        status = c("Observed", "Observed", "Actual", "Actual")) 

plt_data[3:4,5:6] <- NA

ggplot(plt_data, aes(x = status, y = Prevalence, fill = x, group = x, alpha = status)) +
  geom_col(position = position_dodge(width = 1)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, position = position_dodge(width = 1)) +
  labs(title = "Estimated Prevalence", fill = "X") +
  theme(axis.title.x = element_blank(), legend.position = "bottom")+
  scale_alpha_manual(values = c(0.5, 1), guide = "none") + 
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylim(c(0,0.2))

plt_data[3:4,4] <- NA

ggplot(plt_data, aes(x = status, y = Prevalence, fill = x, group = x, alpha = status)) +
  geom_col(position = position_dodge(width = 1)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25, position = position_dodge(width = 1)) +
  labs(title = "Estimated Prevalence", fill = "X") +
  theme(axis.title.x = element_blank(), legend.position = "bottom")+
  scale_alpha_manual(values = c(0.5, 1), guide = "none") + 
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylim(c(0,0.2))
```


## Representativeness


```{r fig.height=3, fig.width=6}
diseased <- df %>% filter(disease == TRUE) %>%
  mutate(group = "Individuals with Disease", alpha = 0.7)

diagnosed <- df %>% filter(diagnosed == TRUE) %>%
  mutate(group = "Individuals Diagnosed", alpha = 1)

plt_data <- rbind(diseased, diagnosed)

ggplot(plt_data, aes(x = representativeness, group = group, alpha = group, fill = x)) +
  geom_histogram(position = "identity") +
  scale_alpha_manual(values = c(1, 0.5)) +
  labs(title = "Distribution of disease representativeness", x = "Representativeness", y = "Number of individuals") +
  theme(legend.title = element_blank()) +
    scale_fill_brewer(palette = "Set1", direction = -1, guide = "none") +
  facet_wrap(~x)

ggplot(plt_data, aes(x = representativeness, group = group, alpha = group, fill = x)) +
  geom_histogram(position = "identity") +
  scale_alpha_manual(values = c(1, 0)) +
  labs(title = "Distribution of disease representativeness", x = "Representativeness", y = "Number of individuals") +
  theme(legend.title = element_blank())+
  scale_fill_brewer(palette = "Set1", direction = -1, guide = "none") +
  facet_wrap(~x)

```


# Case 2: Evidence based medicine

## Doctors all have the same habits

```{r}
simulate_EBM_docs_vary <- function(sigma, n_docs, patients_per_doc = 300,
                                   years = 10, evidence_rate = 0.1){
  for (i in 1:years){
    # generate undiagnosed data
    curr_df <- generate_cs_with_doctors(patients_per_doc, n_docs, sigma = sigma) %>%
      mutate(study_id = i - 1)
  
    if (i == 1){
      # first year, let docs diagnose based on own preferences
      curr_df <- diagnose_cs_with_doctors(curr_df) %>%
        mutate(p_model = NA, p_doc = p_diagnose) %>%
        select(x, disease, representativeness, doctor_id, beta0, betaR, betaX,
               study_id, p_model, p_doc, p_diagnose, diagnosed)
      
      full_df <- curr_df
      
    } else{
      # subsequent years, docs increasingly diagnose based on model
      # TODO: make this something more realistic/flexible
      evidence_weight <- (i - 1)*evidence_rate
      
      nrows <- dim(curr_df)[1]

      # diagnose patients
      curr_df <- curr_df %>%
        mutate(p_model = predict(curr_model, newdata = curr_df, type = "response")) %>%
        mutate(p_doc = diagnosis_fn_by_betas(representativeness, x, beta0, betaR, betaX)) %>%
        mutate(p_diagnose = (1 - evidence_weight)*p_doc + evidence_weight*p_model) %>%
        mutate(diagnosed = rbinom(nrows, size = 1, prob = p_diagnose))
      
      # store results
      full_df <- rbind(full_df, curr_df)
    }
  # build EBM model based on this year's diagnosis
  curr_model <- glm(diagnosed ~ x + representativeness, data = curr_df, family = "binomial")
  }
  return(full_df)
}
```



```{r}
set.seed(1243)
time_df <- simulate_EBM_docs_vary(sigma = 5, n_docs = 25, patients_per_doc = 700, years = 10)
```

```{r fig.height=3, fig.width=7}
plt_data <- time_df %>%
  filter(disease == TRUE) %>%
  group_by(x, study_id, doctor_id) %>%
  summarize(correct_diagnosis_rate = mean(diagnosed == 1),
            beta0 = first(beta0), 
            betaR = first(betaR),
            betaX = first(betaX)) %>%
  mutate(x = as.factor(x))

ggplot(plt_data, aes(x = study_id, y = correct_diagnosis_rate, group = doctor_id, color = x)) +
  geom_line(alpha = 0.5) +
  facet_wrap(~x) + 
  scale_x_continuous(name = "Years of Study", breaks = 0:9) +
  scale_y_continuous(name = "Correct Diagnosis Rate",
                     limits = c(0,0.9),
                     breaks = seq(0, 0.9, by = 0.1),
                     labels = scales::percent_format(accuracy = 1)) +
  scale_color_brewer(palette = "Set1", direction = -1)
```


```{r fig.height=3, fig.width=7}
plt_data <- time_df %>%
  filter(disease == TRUE) %>%
  group_by(x, study_id, doctor_id) %>%
  summarize(correct_diagnosis_rate = mean(diagnosed == 1),
            beta0 = first(beta0), 
            betaR = first(betaR),
            betaX = first(betaX)) %>%
  mutate(x = as.factor(x)) %>%
  mutate(correct_diagnosis_rate = ifelse(study_id > 0, NA, correct_diagnosis_rate))

ggplot(plt_data, aes(x = study_id, y = correct_diagnosis_rate, group = doctor_id, color = x)) +
  geom_point(alpha = 0.5, size = 1) +
  facet_wrap(~x) + 
  scale_x_continuous(name = "Years of Study", breaks = 0:9) +
  scale_y_continuous(name = "Correct Diagnosis Rate",
                     limits = c(0,0.9),
                     breaks = seq(0, 0.9, by = 0.1),
                     labels = scales::percent_format(accuracy = 1)) +
  scale_color_brewer(palette = "Set1", direction = -1)
```

```{r setup params}
n_docs <- 200
patients_per_doc <- 1000
```

### Phi

```{r}
df <- generate_cs_with_doctors(patients_per_doc, n_docs, sigma = 5) %>%
  diagnose_cs_with_doctors()

doc_params <- df %>% 
  group_by(doctor_id) %>% 
  summarize(beta0 = first(beta0), betaR = first(betaR), betaX = first(betaX))
```

```{r fig.height=3, fig.width=6}
R <- seq(0, 1, length.out = 100)
sample_docs <- expand.grid(R, c(0,1), c(1:5)) %>%
  rename(R = Var1, X = Var2, doctor_id = Var3) %>%
  left_join(doc_params, by = "doctor_id") %>%
  mutate(p_diagnose = diagnosis_fn_by_betas(R, X, beta0, betaR, betaX))

ggplot(sample_docs, aes(x = R, y = p_diagnose, group = doctor_id, color = as.factor(X))) +
  geom_line() + 
  facet_wrap(~X) +
  scale_color_brewer(palette = "Set1", direction = -1) +
  ylab("P(Diagnosis | R)")
```


# Case 4: Longitudinal Patient experience

```{r}
set.seed(126)
eg_long <- generate_longitudinal(n = 20)
```

```{r}
ggplot(eg_long, aes(x = t, y = representativeness, group = id, color = as.factor(x))) +
  geom_line() +
  scale_color_brewer(palette = "Set1", direction = -1, guide = "none") +
  labs(y = "Representativeness", x = "Time") 
```

```{r}
eg_diagnosed <- diagnose_longitudinal(eg_long)

diagnosis_pts <- eg_diagnosed %>%
  group_by(id) %>%
  arrange(-diagnosed, t) %>%
  slice_head(1)
```


```{r}
ggplot(eg_diagnosed,
       aes(x = t, y = representativeness, group = id, color = as.factor(x), alpha = diagnosed)) +
  geom_line() +
  geom_point(data = diagnosis_pts, mapping = aes(x = t, y = representativeness)) +
  scale_color_brewer(palette = "Set1", direction = -1, guide = "none") +
  facet_wrap(~x) +
  labs(y = "Representativeness", x = "Time") +
  scale_alpha_manual(values = c(0.2, 1), guide = "none")
```
