# ------------------------------------------------------------------------------
# DIAGNOSE DATA
# ------------------------------------------------------------------------------

#' Diagnose Cross-sectional dataset
#'
#' Add diagnosis labels (0 or 1) to each individual in a cross-sectional dataset
#'
#' @param df cross-sectional dataset
#' @param theta, parameters for diagnosis function
#'
#' @return diagnosed cross_sectional data set.
#' @export
diagnose_cross_sectional <- function(df, theta = c(-10, 20, -5)){
  n_row <- dim(df)[1]

  result <- df %>%
    mutate(p_diagnose = diagnosis_fn(severity, x, theta)) %>%
    mutate(diagnosed = rbinom(n_row, size = 1, p = p_diagnose))

  return(result)
}

#' Test Cross-sectional dataset
#'
#' Add testing and diagnosis labels (0 or 1) to each individual in a
#' cross-sectional dataset
#'
#' @param df cross-sectional dataset
#' @param theta, parameters for diagnosis function
#'
#' @return diagnosed cross_sectional data set.
#' @export
test_cross_sectional <- function(df, theta = c(-10, 20, -5)){
  n_row <- dim(df)[1]

  result <- df %>%
    mutate(p_diagnose = diagnosis_fn(severity, x, theta)) %>%
    mutate(tested = rbinom(n_row, size = 1, p = p_diagnose)) %>%
    mutate(diagnosed = tested & disease)

  return(result)
}


#' Diagnose Cross-sectional dataset with doctor variation
#'
#' Add diagnosis labels (0 or 1) to each individual in a cross-sectional dataset
#'
#' @param df cross-sectional dataset generated by \code{\link{generate_cs_with_doctors}}
#'
#' @return diagnosed cross_sectional data set.
#' @export
diagnose_cs_with_doctors <- function(df){
  n_row <- dim(df)[1]

  result <- df %>%
    mutate(p_diagnose = diagnosis_fn_by_betas(severity, x,
                                              b0 = beta0,
                                              bS = betaS,
                                              bX = betaX)) %>%
    mutate(diagnosed = rbinom(n_row, size = 1, p = p_diagnose))

  return(result)
}



#' Diagnose Longitudinal Data Set
#'
#' At each time point for each individual, calculate probability of diagnosis
#' using diagnosis_fn.  If that individual is not yet diagnosed, check if a new
#' diagnosis would happen at this time point based on the diagnosis probability.
#'
#' @param df longitudinal dataset
#' @param theta parameters for diagnosis function
#'
#' @return diagnosed longitudinal data set.
#' @export
diagnose_longitudinal <- function(df, theta = c(-10, 20, -5)){
  n_row <- dim(df)[1]

  result <- df %>%
    mutate(diagnosed = 0,
           p_diagnose = diagnosis_fn(severity, x, theta)) %>%
    mutate(newly_diagnosed = rbinom(n_row, size = 1, p = p_diagnose)) %>%
    group_by(id) %>%
    mutate(diagnosed = (cumsum(newly_diagnosed) > 0)) %>%
    ungroup()

  return(result)
}

#' Calculate Diagnosis Probability
#'
#' @param x binary covariate
#' @param severity disease severity (in [0,1])
#' @param theta numeric vector giving parameters of diagnostic function
#'
#' @return diagnosis probability between 0 and 1.
#' @export
diagnosis_fn <- function(severity, x, theta = c(-10, 20, -5)){
  c <- 1/(1 + exp(-(theta[1] + theta[3] * x)))

  return(1/(1 + exp(-(theta[1] + theta[2] * severity + theta[3] * x))) - c)
}

#' Calculate Diagnosis Probability
#'
#' @param x binary covariate
#' @param severity disease severity (in [0,1])
#' @param b0 beta coefficient for intercept of diagnostic function
#' @param bS beta coefficient for severity in diagnostic function
#' @param bX beta coefficient for X in diagnostic function
#'
#' @return diagnosis probability between 0 and 1.
#' @export
diagnosis_fn_by_betas <- function(severity, x, b0 = -10, bS = 20, bX = -5){
  c <- 1/(1 + exp(-(b0 + bX * x)))

  return(1/(1 + exp(-(b0 + bS * severity + bX * x))) - c)
}
